# -*- coding: utf-8 -*-
"""EE456_ImageFormat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQ18HG35skSGH0xXkTv210P-kUag3ECq
"""

#Not requried if running localy
# from google.colab import drive
# drive.mount('/content/drive')

#imports
import zipfile
import os
import json
import pandas as pd
import cv2
import numpy as np
import matplotlib.pyplot as plt
from concurrent.futures import ProcessPoolExecutor

zip_file_path = 'osu-small-animals-lila.zip'

# Define the extraction path
extraction_path = 'extracted_files'

# Ensure the directory exists
os.makedirs(extraction_path, exist_ok=True)

# Extract the ZIP file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f'Files extracted to: {extraction_path}')

# Path to your JSON file
json_file_path = 'osu-small-animals.json'

# Load the JSON file
with open(json_file_path, 'r') as file:
    data = json.load(file)

# Print or inspect the data
print(data)

# Define the root directory (update this path)
root_dir = "osu-small-animals-lila/Images/Sorted_by_species"

# Initialize lists to store file names and paths
file_names = []
file_paths = []
species_folders = []

# Iterate through the 7 folders in the root directory
for folder in os.listdir(root_dir):
    print(folder)
    i = 0
    # Check if it's a directory
    folder_path = os.path.join(root_dir, folder)
    for folder2 in os.listdir(folder_path):
      i += 1
      j = 0
      folder_path2 = os.path.join(folder_path, folder2)
      if folder2.lower().endswith(('.png', '.jpg', '.jpeg')):
                  file_names.append(folder2)
                  file_paths.append(os.path.join(folder_path, folder2))
                  species_folders.append(folder2)
      if os.path.isdir(folder_path2):  # Ensure it's a directory
          for file in os.listdir(folder_path2):
              # Only process image files (filter by extensions if needed)

              if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                  file_names.append(file)
                  file_paths.append(os.path.join(folder_path2, file))
                  species_folders.append(folder2)

    print(i)
# Create a DataFrame
df = pd.DataFrame({
    "file_name": file_names,
    "file_path": file_paths
})

# Display the first few rows of the DataFrame
#df[20:]

#data.keys()

df_annotations = pd.DataFrame(data['annotations'])
#df_annotations

#get only the file name so we can map it to the path we have.
df_annotations['id'] = df_annotations['id'].apply(lambda x: x.split('/')[-1])

#remove unecesarry columns
df_annotations = df_annotations.drop(columns=["image_id", "sequence_level_annotation"])

#remove all the blank images as we will not be considering those for this project.
df_annotations = df_annotations[df_annotations['category_id'] != 0]
# Display the updated DataFrame
#df_annotations

merged_df = pd.merge(
    df, df_annotations,
    left_on="file_name", right_on="id",
    how="inner"  # Use "inner" to keep only matching rows
)

# Display the merged DataFrame
merged_df['category_id'] = merged_df['category_id'] - 1
#merged_df

merged_df.to_csv('labels.csv')

df_category = pd.DataFrame(data['categories'])
#df_category

close_to_endangered_species = [
    "northern_leopard_frog", "meadow_jumping_mouse", "american_mink",
    "eastern_bluebird", "gray_catbird", "song_sparrow", "striped_skunk", "painted_turtle", "gray_ratsnake", "eastern_milksnake"
]

# Create a new 'endangered' column
df_category['endangered'] = df_category['name'].apply(lambda x: 1 if x in close_to_endangered_species else 0)

# Display the updated DataFrame
# df_category

df_category.to_csv('category_annot.csv')

def apply_edge_detection(image_path):
    # Load image
    img = cv2.imread(image_path, cv2.IMREAD_COLOR)

    if img is None:
        print(f"Error: Unable to load image from path: {image_path}")
        return None

    # Resize the image to a fixed size (optional)
    img = cv2.resize(img, (128, 128))  # Only resize if necessary

    # Convert to grayscale for edge detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply edge detection using Canny filter
    edges = cv2.Canny(gray, 100, 200)

    edges = np.expand_dims(edges, axis=-1)

    return edges

def process_images_in_parallel(image_paths):
    # Using ProcessPoolExecutor for parallel image processing
    with ProcessPoolExecutor() as executor:
        results = list(executor.map(apply_edge_detection, image_paths))

    return results


image_paths = list(merged_df['file_path'])
X = process_images_in_parallel(image_paths)

np.savez_compressed('X_data_edges.npz', X=X)

###Test Code
# import cv2
# import matplotlib.pyplot as plt
# import numpy as np
# from concurrent.futures import ProcessPoolExecutor

# def display_rescaled_image(image_path):
#     # Load the image
#     img = cv2.imread(image_path, cv2.IMREAD_COLOR)

#     if img is None:
#         print(f"Error: Unable to load image from path: {image_path}")
#         return

#     # Resize the image to 128x128
#     img_resized = cv2.resize(img, (128, 128))

#     # Convert the image from BGR to RGB (OpenCV uses BGR by default)
#     img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)


#     return img_rgb

# def process_images_in_parallel(image_paths):
#   # Using ProcessPoolExecutor for parallel image processing
#   with ProcessPoolExecutor() as executor:
#       results = list(executor.map(display_rescaled_image, image_paths))

#   return results


# image_paths = list(merged_df['file_path'])
# X_Colored = process_images_in_parallel(image_paths)

#np.savez_compressed('/content/drive/My Drive/X_data_grey.npz', X=X_Colored)