# -*- coding: utf-8 -*-
"""EE456FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwPYTvU14zMO2XK4KCtZ_RyGGM45RJJw

# Load Data and Prepare for CNN model
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Load the .npz file
X = np.load('X_data_edges.npz')['X']
X = X.reshape((X.shape[0], 1, 128, 128))

labels = pd.read_csv('labels.csv')

#labels.head()

y = np.array(labels['category_id'])

# Custom Dataset Class
class ImageDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        try:
            img = self.X[idx]
            label = self.y[idx]
        except IndexError:
            raise IndexError(f"Index {idx} is out of bounds for the dataset of size {len(self.X)}")
        except KeyError:
            raise KeyError(f"KeyError at index {idx}. Dataset X has shape {self.X.shape}, y has length {len(self.y)}")

        img = torch.tensor(img, dtype=torch.float32)
        label = torch.tensor(label, dtype=torch.long)
        return img, label

# CNN Model Architecture
class CNNModel(nn.Module):
    def __init__(self, num_classes):
        super(CNNModel, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(128 * 16 * 16, 512)
        self.fc2 = nn.Linear(512, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))

        x = x.view(-1, 128 * 16 * 16)  # Flatten the output
        x = F.relu(self.fc1(x))
        x = self.fc2(x)

        return x

# Normalize X
X = X.astype('float32') / 255.0

# Train-validation split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Prepare DataLoader
train_dataset = ImageDataset(X_train, y_train)
val_dataset = ImageDataset(X_val, y_val)

batch_size = 64 if len(train_dataset) >= 64 else len(train_dataset)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)

batch_size = 64 if len(val_dataset) >= 64 else len(val_dataset)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)

# Define the Model, Loss, and Optimizer
num_classes = len(np.unique(y))
model = CNNModel(num_classes=num_classes)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training and Evaluation Loop
epochs = 10
top_5_scores = []

train_accuracies = []
val_accuracies = []

print('Start training')
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct_train = 0
    total_train = 0

    # Train loop
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()

    train_acc = 100 * correct_train / total_train
    train_accuracies.append(train_acc)

    # Validation loop
    model.eval()
    correct_val = 0
    total_val = 0
    val_loss = 0.0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)

            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            total_val += labels.size(0)
            correct_val += (predicted == labels).sum().item()

            # Store top 5 confidence scores

            for output, label in zip(outputs, labels):
                scores, indices = torch.topk(F.softmax(output, dim=0), 5)
                top_5_scores.append({
                    'true_label': label.item(),
                    'predicted_labels': indices.cpu().numpy(),
                    'confidence_scores': scores.cpu().numpy()
                })

    val_acc = 100 * correct_val / total_val
    val_accuracies.append(val_acc)

    # Print Epoch Statistics
    print(f"Epoch [{epoch + 1}/{epochs}], "
          f"Train Loss: {running_loss / len(train_loader):.4f}, "
          f"Train Accuracy: {train_acc:.2f}%, "
          f"Val Loss: {val_loss / len(val_loader):.4f}, "
          f"Val Accuracy: {val_acc:.2f}%")

# Plot Accuracy Graph
plt.plot(train_accuracies, label="Train Accuracy")
plt.plot(val_accuracies, label="Validation Accuracy")
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Epoch vs Accuracy')
plt.legend()
plt.show()

# Example: Print stored top 5 confidence scores for the first few images
for i, score in enumerate(top_5_scores[:5]):
    print(f"Image {i + 1}:")
    print(f"True Label: {score['true_label']}")
    print(f"Predicted Labels: {score['predicted_labels']}")
    print(f"Confidence Scores: {score['confidence_scores']}")
    print('-' * 50)

"""# Format and prepare data for Endangered Prediction Pipeline"""

endangered_dict = {'confidence scores': [], 'predicted labels': [], 'label': []}

endangered_dict['confidence scores'] = [top['confidence_scores'] for top in top_5_scores]
endangered_dict['predicted labels'] = [top['predicted_labels'] for top in top_5_scores]
endangered_dict['labels'] = [top['true_label'] for top in top_5_scores]

end_df = pd.DataFrame()
end_df['predicted labels'] = endangered_dict['predicted labels']
end_df['confidence scores'] = endangered_dict['confidence scores']
end_df['labels'] = endangered_dict['labels']
#end_df

category_df = pd.read_csv('category_annot.csv')

category_df.drop(columns=['Unnamed: 0'], inplace=True)

#category_df

# Merge the DataFrames
merged_df2 = end_df.merge(category_df, left_on='labels', right_on='id', how='left')

merged_df2.drop(columns=['id', 'latin_name', 'name'], inplace=True)
# Result
#merged_df2

# Split 'file_name' into parts by '/' and store the 5th and 6th parts in new columns
labels[['category', 'species']] = labels['file_path'].str.split('/', expand=True)[[6, 7]]

# Convert 'category' and 'species' to lowercase (optional, based on your requirement)
labels['category'] = labels['category'].str.lower()
labels['species'] = labels['species'].str.lower()

category_id_df_sorted = category_id_df.sort_values(by='category_id').reset_index(drop=True)

# Print the resulting sorted DataFrame
#category_id_df_sorted

# Merge the DataFrames
merged_df3 = merged_df2.merge(category_id_df_sorted, left_on='labels', right_on='category_id', how='left')

merged_df3.drop(columns=['category_id'], inplace=True)

# Initialize the LabelEncoder
le = LabelEncoder()

# Fit and transform the 'category' column to encode categorical values into numerical values
merged_df3['category_encoded'] = le.fit_transform(merged_df3['category'])

#Display
#merged_df3[['category', 'category_encoded']]

"""# Endangered Prediction Model"""

# Custom Dataset Class
class AnimalDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        img = self.X[idx]
        label = self.y[idx]

        img = torch.tensor(img, dtype=torch.float32)
        label = torch.tensor(label, dtype=torch.long)

        return img, label

# Neural Network Model
class NNModel(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NNModel, self).__init__()

        # Define a simple feed-forward neural network
        self.fc1 = nn.Linear(input_size, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x

# Assuming predicted_labels, confidence_scores, category_encoded, and endangered are your feature and target variables
# Convert to a DataFrame
data = merged_df3[['predicted labels', 'confidence scores', 'category_encoded', 'endangered']]

def combine_features(pred_labels, conf_scores, category_encoded):
    """Combine predicted labels, confidence scores, and category encoded into a single feature vector."""
    combined_features = []

    for label_list, score_list, cat in zip(pred_labels, conf_scores, category_encoded):
        # Flatten the label and score lists, and add the category
        feature_vector = list(label_list) + list(score_list) + [cat]
        combined_features.append(feature_vector)

    # Convert the list of feature vectors into a numpy array with shape (num_samples, num_features)
    return np.array(combined_features)

# Combine the features
X = combine_features(data['predicted labels'], data['confidence scores'], data['category_encoded'])

# Prepare the target variable (y)
y = data['endangered'].values

# Ensure y is a 1D array
y = np.array(y).reshape(-1)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Create PyTorch datasets and dataloaders
train_dataset = AnimalDataset(X_train, y_train)
val_dataset = AnimalDataset(X_val, y_val)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False, num_workers=0)

# Define the model, loss function, and optimizer
input_size = X_train.shape[1]  # Number of features in each input (predicted label + confidence score + category_encoded)
num_classes = len(np.unique(y))  # Number of unique target values (2 in this case: 0 and 1)
model = NNModel(input_size=input_size, num_classes=num_classes)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training and evaluation loop
epochs = 100
train_accuracies = []
val_accuracies = []

print('Start training')

for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct_train = 0
    total_train = 0

    # Train loop
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()

    train_acc = 100 * correct_train / total_train
    train_accuracies.append(train_acc)

    # Validation loop
    model.eval()
    correct_val = 0
    total_val = 0
    val_loss = 0.0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            total_val += labels.size(0)
            correct_val += (predicted == labels).sum().item()

    val_acc = 100 * correct_val / total_val
    val_accuracies.append(val_acc)

    # Print Epoch Statistics
    if epoch%10 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], "
              f"Train Loss: {running_loss / len(train_loader):.4f}, "
              f"Train Accuracy: {train_acc:.2f}%, "
              f"Val Loss: {val_loss / len(val_loader):.4f}, "
              f"Val Accuracy: {val_acc:.2f}%")

# Plot Accuracy Graph
import matplotlib.pyplot as plt
plt.plot(train_accuracies, label="Train Accuracy")
plt.plot(val_accuracies, label="Validation Accuracy")
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Epoch vs Accuracy')
plt.legend()
plt.show()

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_val)

# Step 4: Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Step 5: Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Step 6: Evaluate the model
accuracy = accuracy_score(y_val, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Confusion matrix to visualize the classification results
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# Classification report for detailed performance metrics
print("Classification Report:")
print(classification_report(y_val, y_pred))

# Optional: If you want to check model coefficients (weights) and the intercept
print(f'Coefficients: {model.coef_}')
print(f'Intercept: {model.intercept_}')

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)

y_pred = rf_model.predict(X_test_scaled)

accuracy = accuracy_score(y_val, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# Classification report for detailed performance metrics
print("Classification Report:")
print(classification_report(y_val, y_pred))
print(f'Feature Importances: {rf_model.feature_importances_}')

svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_scaled, y_train)


y_pred = svm_model.predict(X_test_scaled)


accuracy = accuracy_score(y_val, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')


print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))


print("Classification Report:")
print(classification_report(y_val, y_pred))
print(f'Support Vectors: {len(svm_model.support_)}')

